# Generated by Django 6.0.1 on 2026-01-26 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 3 horas, 6 horas, Noche completa', max_length=100)),
                ('horas', models.PositiveIntegerField(help_text='Duración base de la tarifa en horas')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Costo de la tarifa.', max_digits=10)),
                ('es_nocturna', models.BooleanField(default=False, help_text='Indica si esta tarifa aplica solo en un horario nocturno específico.')),
                ('hora_inicio_nocturna', models.TimeField(blank=True, help_text='Hora de inicio si la tarifa es nocturna (ej. 21:00).', null=True)),
                ('hora_fin_nocturna', models.TimeField(blank=True, help_text='Hora de fin si la tarifa es nocturna (ej. 10:00).', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la tarifa está disponible para ser usada en nuevas estancias.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='habitaciones.tipohabitacion')),
            ],
            options={
                'permissions': [('crear_tarifa', 'Puede crear tarifas'), ('editar_tarifa', 'Puede editar tarifas'), ('ver_tarifas', 'Puede ver tarifas'), ('desactivar_tarifa', 'Puede desactivar tarifas')],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tipo_habitacion'), name='unique_tarifa_por_tipo_habitacion')],
            },
        ),
    ]
