# Generated by Django 6.0.1 on 2026-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la tarifa está disponible para ser usada en nuevas estancias.'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='es_nocturna',
            field=models.BooleanField(default=False, help_text='Indica si esta tarifa aplica solo en un horario nocturno específico.'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='hora_fin_nocturna',
            field=models.TimeField(blank=True, help_text='Hora de fin si la tarifa es nocturna (ej. 10:00).', null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='hora_inicio_nocturna',
            field=models.TimeField(blank=True, help_text='Hora de inicio si la tarifa es nocturna (ej. 21:00).', null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Costo de la tarifa.', max_digits=10),
        ),
    ]
