# Generated by Django 6.0.1 on 2026-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el usuario puede iniciar sesión. Desmarcar en lugar de borrar.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado'), ('INVITADO', 'Invitado')], default='EMPLEADO', help_text='Rol del usuario dentro del sistema, determina sus permisos.', max_length=20),
        ),
    ]
