# Generated by Django 6.0.1 on 2026-01-26 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre único para el tipo de habitación (ej. 'Suite Presidencial').", max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de las características del tipo de habitación.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo de habitación está disponible para ser usado.')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número único que identifica la habitación.', unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la habitación está operativa y puede ser asignada a una estancia.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='habitaciones.tipohabitacion')),
            ],
        ),
    ]
