# Generated by Django 6.0.1 on 2026-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('LIMPIEZA', 'En Limpieza'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', help_text='Estado operativo actual de la habitación.', max_length=20),
        ),
    ]
