# Generated by Django 6.0.1 on 2026-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la habitación está operativa y puede ser asignada a una estancia.'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número único que identifica la habitación.', unique=True),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si este tipo de habitación está disponible para ser usado.'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de las características del tipo de habitación.'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(help_text="Nombre único para el tipo de habitación (ej. 'Suite Presidencial').", max_length=50, unique=True),
        ),
    ]
