# Generated by Django 6.0.1 on 2026-01-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del producto.', max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto.', max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está disponible para la venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
