# Generated by Django 6.0.1 on 2026-01-26 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now, help_text='Hora en que el cliente ingresó a la habitación')),
                ('hora_salida_programada', models.DateTimeField(help_text='Hora calculada según tarifa y horas extra. Se actualiza si se agregan horas extras')),
                ('hora_salida_real', models.DateTimeField(blank=True, help_text='Hora real en que el cliente salió', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la estancia está actualmente en curso.')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='habitaciones.habitacion')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='tarifas.tarifa')),
            ],
            options={
                'permissions': [('abrir_estancia', 'Puede abrir una estancia'), ('cerrar_estancia', 'Puede cerrar una estancia'), ('ver_estancias', 'Puede ver estancias')],
            },
        ),
    ]
