# Generated by Django 6.0.1 on 2026-01-22 03:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0002_turno_diferencia_turno_efectivo_esperado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.PositiveIntegerField()),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('horas_base', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='turnos.turno')),
            ],
        ),
    ]
