# Generated by Django 6.0.1 on 2026-01-23 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='habitaciones.habitacion')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='tarifas.tarifa')),
            ],
            options={
                'permissions': [('abrir_estancia', 'Puede abrir una estancia'), ('cerrar_estancia', 'Puede cerrar una estancia'), ('ver_estancias', 'Puede ver estancias')],
            },
        ),
    ]
