# Generated by Django 6.0.1 on 2026-01-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancia',
            name='turno_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estancias_cerradas', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='turno_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias_iniciadas', to='turnos.turno'),
        ),
        migrations.AddConstraint(
            model_name='estancia',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('habitacion',), name='unique_estancia_activa_por_habitacion'),
        ),
    ]
