# Generated by Django 6.0.1 on 2026-01-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0001_initial'),
        ('turnos', '0002_turno_diferencia_turno_efectivo_esperado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extra', to='estancias.estancia')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extra', to='turnos.turno')),
            ],
        ),
    ]
