# Generated by Django 6.0.1 on 2026-01-26 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estancia',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la estancia está actualmente en curso.'),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Hora en que el cliente ingresó a la habitación'),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='hora_salida_programada',
            field=models.DateTimeField(help_text='Hora calculada según tarifa y horas extra. Se actualiza si se agregan horas extras'),
        ),
    ]
