# Generated by Django 6.0.1 on 2026-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche')], max_length=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('sueldo', models.DecimalField(decimal_places=2, default=0, help_text='Sueldo que el empleado toma al cerrar el turno', max_digits=10)),
                ('caja_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Dinero con el que inicia la caja', max_digits=10)),
                ('efectivo_esperado', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo que debería haber en caja', max_digits=10, null=True)),
                ('efectivo_reportado', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado al cierre', max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia entre esperado y reportado', max_digits=10, null=True)),
                ('caja_final', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo final en caja', max_digits=10, null=True)),
            ],
            options={
                'permissions': [('abrir_turno', 'Puede abrir turno'), ('cerrar_turno', 'Puede cerrar turno'), ('ver_turnos', 'Puede ver turnos')],
            },
        ),
    ]
