# Generated by Django 6.0.1 on 2026-01-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario',), name='unique_turno_activo_por_usuario'),
        ),
    ]
