# Generated by Django 6.0.1 on 2026-01-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia entre efectivo esperado y reportado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='efectivo_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo que debería haber en caja', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='efectivo_reportado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo que el empleado dice haber contado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='caja_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo final reportado en caja', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='caja_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero con el que inicia la caja', max_digits=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sueldo que el empleado toma al cerrar el turno', max_digits=10),
        ),
    ]
