# Generated by Django 6.0.1 on 2026-01-26 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_turno_activo_por_usuario',
        ),
        migrations.AlterField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el turno está actualmente en curso.'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='caja_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo final en caja después de tomar el sueldo (es igual al efectivo reportado).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='caja_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero con el que el empleado inicia la caja.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia entre el efectivo esperado y el reportado.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='efectivo_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cálculo del efectivo que debería haber en caja al cierre.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='efectivo_reportado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo que el empleado contó físicamente al cierre.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se cerró el turno. Nulo si está activo.', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se inició el turno.'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sueldo que el empleado reporta haber tomado al cerrar el turno.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo_turno',
            field=models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche')], help_text='Indica si el turno es de día o de noche.', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(help_text='Empleado responsable del turno.', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
