# Generated by Django 6.0.1 on 2026-01-22 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_diferencia_turno_efectivo_esperado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='unique_turno_activo'),
        ),
    ]
